'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css"
import Layout from "@/components/Layout";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {  

  const pathname=usePathname()
  const [loading,setLoading] = useState(true)  
  
  useEffect(()=>{
      setLoading(false)
      // console.log(loading);
    
  },[children])

  if (loading) {
    return (
      <html lang="en">
      <body className={inter.className}>
      <div className="loading-wrap">
        <div className="loading"></div>
        <div className="loading-text">loading...</div>
      </div>
      </body>
    </html>
    )
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        {(pathname==='/login'||pathname==='/sign')?
        <div>{children}</div>:
        <Layout>
        {children}
        </Layout>
        }
        
      </body>
    </html>
  );
}
